FROM openjdk:8-jre-alpine

LABEL maintainer=manokrrish@gmail.com


COPY ./message-stream-service-0.0.1-SNAPSHOT.jar /mss.jar

#CMD echo "mss.jar is shipped"

CMD /usr/bin/java -jar mss.jar

#CMD echo "message-stream-service started..."


